### PR TITLE
Standalone Javascript plugin

### PR DESCRIPTION
**Pull request by Multi-Thinker**
- Vanilla JS plugin with new of features such as bind/unbind
- Change for languages
- better input options
- helper buttons such as EN/UR or layout. 
- zero configuration

### CODE REVIEW

**Comment by awaisathar** [comment]
There's no support for textarea and if the input element is placed in a form, it  submits the form. 
Also, are you sure you want this as part of the jquery plugin and not a separate repo?

**Review by Multi-Thinker — COMMENTED** [review]
1. fixed button submit bug
2. added multi input support, user words written in Urdu will not get converted in English, or written in English will not get converted in Urdu when changing languages. 
3. textarea supported. 
4. fixed and improved jQuery plugin to support two languages 

working demo for JS: https://codepen.io/iMultiThinker/full/YBVVyy 
working demo for jQuery: https://codepen.io/iMultiThinker/full/exGLGp

PS: Yet Another Urdu Keyboard can hold JS files too as the name doesn't state jQuery only urdu keyboard, and it could be a good plus for people who don't want to include additional jquery for this functionality.

**Comment by awaisathar** [comment]
Agreed. But lets keep the multi-language support as well as showing of keyboard optional.
Let me close this merge and add issues as feature requests and the we can perhaps do a pull request against each issue. Also, currently doing a double-click select-all and writing over it doesn't work.  Additionally, I am not sure about the reason for using insertAtCursor(myField, myValue, old) as well as it's license :)

**Comment by Multi-Thinker** [comment]
Pardon for the additional bugs, i needed to create an urdu keyboard having such behavior. I've updated some stuff on my pen and was wondering if it would benefit this repo.  

1. ```insertAtCursor``` is basically placing our "glyphs" instead of the default browser language to the instance of ```this.value```, recently you were creating an array out of this.value and parsing all alphabets to urdu which was a bug if you needed to add english inside your urdu, such as some foreign words as Google, IBM etc
2. I have now updated my pens to support other browsers as "input" event is not fully supported for firefox the ```event.data``` is not an object of event instance for keypress. 
3. i have also fixed the selection problem on my pens, now you can place cursor or select the text to type
4. i can simple set "false" to the "optional" features such as layout and languages and create a pull request against the issues you created if you find my versions suitable enough. 
5. additionally some glyphs such as "zer, zabar, pesh" were written in UTF format in javascript, I've converted them to unicodes in my minified file to support older browsers. 

i would love to contribute on this project and keep it alive as it is the only urdu keyboard plugin i found useful.. let me know if there are any errors or cross-browser problem as i've only developed this to support my initial scenario, ran only on modern browsers. (i actually don't give a care about older browsers such as IE)

about license: https://snipplr.com/view/1384/insertatcursor/  this function was posted in 2010 without any license restriction ever since is being used. 
working demo for JS: https://codepen.io/iMultiThinker/full/YBVVyy
working demo for jQuery: https://codepen.io/iMultiThinker/full/exGLGp

**Comment by awaisathar** [comment]
Let's rewrite insertAtCursor from scratch just to be safe and leave IE. The rest should be okay if we can add one feature at a time, say English support first, while keeping the current features (like the ability to do Ctrl-Z and paste etc). Thanks!

**Pull request closed without merging**
